name: 'trx-parser-test'
description: 'An action to parse trx reports from a given path and use GitHub status check api to fail PRs'
author: 'Nasir Amin'
branding:
  icon: 'info'  
  color: 'green'
inputs:
    TRX_PATH:
      description: 'Path to the directory cntaining trx files'
      required: true
    REPO_TOKEN:
      description: 'Pass in the repository token. This should be generally be secrets.GITHUB_TOKEN. This is used for GitHub checks api'
      required: true
    IGNORE_FAILURE:
      description: 'Set to true if you want test failures not to block the pull requests. The check status will be set to neutral'
      required: false
      default: 'false'
    REPORT_ONLY_FAILED:
      description: 'Report only failed tests. This is useful when running on huge suite and hitting limit of 64k limit of github report page'
      required: false
      default: 'false'

outputs:
  test-outcome:
    description: 'Test outcome Failed/Passed'
  trx-files:
    description: 'list of trx files'
runs:
  using: 'node12'
  main: 'dist/index.js'
