name: 'trx-parser'
description: 'An action to parse trx reports from a given path and use GitHub status check api to fail PRs'
author: 'Nasir Amin'
branding:
  icon: 'info'  
  color: 'green'
inputs:
    TRX_PATH:
      description: 'Path to the directory containing trx files'
      required: true
    REPO_TOKEN:
      description: 'Pass in the repository token. This should be generally be secrets.GITHUB_TOKEN. This is used for GitHub checks api'
      required: true
    IGNORE_FAILURE:
      description: 'Set to true if you want test failures not to block the pull requests. The check status will be set to neutral'
      required: false
      default: 'false'
    SHA:
      description: 'SHA value to use. If not set then will be calculated based on context'
      required: false
outputs:
  test-outcome:
    description: 'Test outcome Failed/Passed'
  trx-files:
    description: 'list of trx files'
runs:
  using: 'node16'
  main: 'dist/index.js'
