name: 'trx-parser'
description: 'An action to parse trx reports from a given path and use GitHub status check api to fail PRs'
author: 'Nasir Amin'
branding:
  icon: 'info'  
  color: 'green'
inputs:
    TRX_PATH:
      description: 'Path to the directory cntaining trx files'
      required: true
    repo-token:
      description: 'Pass in the repository token. This should be generally be secrets.GITHUB_TOKEN. This is used for GitHub checks api'
      required: true
outputs:
  test-outcome:
    description: 'Test outcome Failed/Passed'
  trx-path:
    description: 'Used for debugging'
  trx-files:
    description: 'list of trx files'
runs:
  using: 'node12'
  main: 'dist/index.js'

# ToDO
# Write a test that expects a failure on a failing test in trx
# 
