name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  integration-test:
    name: Integration Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20]

    permissions:
      checks: write
      actions: write
      statuses: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and package
        run: npm run all

      - name: Test with passing results
        id: passing-tests
        uses: ./
        with:
          TRX_PATH: ${{ github.workspace }}/test-data/passing-tests
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPORT_PREFIX: ${{ matrix.os }}-passing

      - name: Test with failing results (expect failure)
        id: failing-tests
        continue-on-error: true
        uses: ./
        with:
          TRX_PATH: ${{ github.workspace }}/test-data/failing-tests
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_FAILURE: true
          REPORT_PREFIX: ${{ matrix.os }}-failing

      - name: Verify test outputs
        shell: bash
        run: |
          echo "Passing tests outcome: ${{ steps.passing-tests.outputs.test-outcome }}"
          echo "Passing tests files: ${{ steps.passing-tests.outputs.trx-files }}"
          echo "Failing tests outcome: ${{ steps.failing-tests.outputs.test-outcome }}"
          echo "Failing tests files: ${{ steps.failing-tests.outputs.trx-files }}"
          echo "Git SHA: ${{ github.sha }}"
          echo "Git ref: ${{ github.ref }}"
          
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "PR head SHA: ${{ github.event.pull_request.head.sha }}"
          fi



