name: Test
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
  create:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:        
        matrix:
          os: [windows-latest, ubuntu-latest]
    steps:
        - name: Get Source Code
          uses: actions/checkout@v2
        - name: Passing Tests
          id: passing-tests
          uses: ./
          with:
            TRX_PATH: ${{ github.workspace }}/test-data/passing-tests
            repo-token: ${{ secrets.GITHUB_TOKEN }}

        - name: Failing tests
          id: failing-tests
          # This one is expected to fail
          continue-on-error: true          
          uses: ./
          with:
            TRX_PATH: ${{ github.workspace }}/test-data/failing-tests
            repo-token: ${{ secrets.GITHUB_TOKEN }}

        - name: Print Test Outcome
          run: |
            echo Outcome is: ${{ steps.passing-tests.outputs.test-outcome }}
            echo Path is: ${{ steps.passing-tests.outputs.trx-path }}
            echo trx files: ${{ steps.passing-tests.outputs.trx-files }}

        - name: Try powershell
          shell: pwsh
          run: |            
            Write-Output 'Testing on: ${{ matrix.os }}'
            Write-Output 'Trasformting trx to md'
            .\trx-reports\sample-test-results.ps1
            ls
            ls trx-reports
            Write-Output 'Powershell test finished'
            cat trx-reports\sample-test.results.md


