name: Test
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:        
        matrix:
          os: [windows-latest, ubuntu-latest]
    permissions:
      checks: write
      actions: write
      statuses: write
      pull-requests: write
    steps:
        - name: Get Source Code
          uses: actions/checkout@v2
        - name: Passing Tests
          id: passing-tests
          uses: ./
          with:
            TRX_PATH: ${{ github.workspace }}/test-data/passing-tests
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            REPORT_PREFIX: ${{ matrix.os }}

        - name: Failing tests
          id: failing-tests
          # This one is expected to fail
          continue-on-error: true          
          uses: ./
          with:
            TRX_PATH: ${{ github.workspace }}/test-data/failing-tests
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            IGNORE_FAILURE: true
            REPORT_PREFIX: ${{ matrix.os }}

        - name: Print Test Outcome
          run: |
            echo Outcome is: ${{ steps.passing-tests.outputs.test-outcome }}
            echo Path is: ${{ steps.passing-tests.outputs.trx-path }}
            echo trx files: ${{ steps.passing-tests.outputs.trx-files }}
            echo head_sha: ${{ github.event.pull_request.head.sha }}
            echo report prefix: ${{ steps.passing-tests.outputs.report-prefix}}
            echo git_sha: ${{ github.sha}}
            echo git_ref: ${{ github.ref}}



